version: 2.1
workflows:
  version: 2
  all:
    jobs:
      - check_url
jobs:
  check_url:
    docker:
    - image: node:10.15.3
    steps:
    - run: curl https://therightboxforbikelocks.boxlocks.rocks/ | grep '<meta http-equiv="Refresh" content="0; url=https://thewirecutter.com/reviews/best-lock-box/" />'
